# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SensorUI.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SensorInterface(object):
    def setupUi(self, SensorInterface):
        SensorInterface.setObjectName("SensorInterface")
        SensorInterface.resize(650, 550)
        font = QtGui.QFont()
        font.setFamily("PibotoLt")
        SensorInterface.setFont(font)
        self.refreshButton = QtWidgets.QPushButton(SensorInterface)
        self.refreshButton.setGeometry(QtCore.QRect(10, 500, 121, 41))
        self.refreshButton.setObjectName("refreshButton")
        self.exitButton = QtWidgets.QPushButton(SensorInterface)
        self.exitButton.setGeometry(QtCore.QRect(520, 500, 121, 41))
        self.exitButton.setAutoDefault(False)
        self.exitButton.setObjectName("exitButton")
        self.temperatureLabel = QtWidgets.QLabel(SensorInterface)
        self.temperatureLabel.setGeometry(QtCore.QRect(90, 80, 91, 91))
        self.temperatureLabel.setText("")
        self.temperatureLabel.setPixmap(QtGui.QPixmap("Icons/temperature.png"))
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.humidityLabel = QtWidgets.QLabel(SensorInterface)
        self.humidityLabel.setGeometry(QtCore.QRect(485, 90, 81, 81))
        self.humidityLabel.setText("")
        self.humidityLabel.setPixmap(QtGui.QPixmap("Icons/humidity.png"))
        self.humidityLabel.setObjectName("humidityLabel")
        self.timeLabel = QtWidgets.QLabel(SensorInterface)
        self.timeLabel.setGeometry(QtCore.QRect(290, 10, 81, 71))
        self.timeLabel.setText("")
        self.timeLabel.setPixmap(QtGui.QPixmap("Icons/clock.png"))
        self.timeLabel.setObjectName("timeLabel")
        self.timeDisplay = QtWidgets.QLineEdit(SensorInterface)
        self.timeDisplay.setGeometry(QtCore.QRect(250, 90, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.timeDisplay.setFont(font)
        self.timeDisplay.setObjectName("timeDisplay")
        self.alertDisplay = QtWidgets.QLineEdit(SensorInterface)
        self.alertDisplay.setGeometry(QtCore.QRect(200, 280, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.alertDisplay.setFont(font)
        self.alertDisplay.setAutoFillBackground(False)
        self.alertDisplay.setObjectName("alertDisplay")
        self.alertLabel = QtWidgets.QLabel(SensorInterface)
        self.alertLabel.setGeometry(QtCore.QRect(285, 200, 91, 81))
        self.alertLabel.setText("")
        self.alertLabel.setPixmap(QtGui.QPixmap("Icons/alert.png"))
        self.alertLabel.setObjectName("alertLabel")
        self.temperatureDisplay = QtWidgets.QLCDNumber(SensorInterface)
        self.temperatureDisplay.setGeometry(QtCore.QRect(60, 180, 151, 61))
        self.temperatureDisplay.setObjectName("temperatureDisplay")
        self.humidityDisplay = QtWidgets.QLCDNumber(SensorInterface)
        self.humidityDisplay.setGeometry(QtCore.QRect(450, 180, 151, 61))
        self.humidityDisplay.setObjectName("humidityDisplay")
        self.celciusButton = QtWidgets.QPushButton(SensorInterface)
        self.celciusButton.setGeometry(QtCore.QRect(30, 180, 31, 31))
        self.celciusButton.setObjectName("celciusButton")
        self.fahrenheitButton = QtWidgets.QPushButton(SensorInterface)
        self.fahrenheitButton.setGeometry(QtCore.QRect(30, 210, 31, 31))
        self.fahrenheitButton.setObjectName("fahrenheitButton")
        self.timerStartButton = QtWidgets.QPushButton(SensorInterface)
        self.timerStartButton.setGeometry(QtCore.QRect(180, 500, 121, 41))
        self.timerStartButton.setObjectName("timerStartButton")
        self.timerStopButton = QtWidgets.QPushButton(SensorInterface)
        self.timerStopButton.setGeometry(QtCore.QRect(350, 500, 121, 41))
        self.timerStopButton.setObjectName("timerStopButton")
        self.graphButton = QtWidgets.QPushButton(SensorInterface)
        self.graphButton.setGeometry(QtCore.QRect(290, 390, 71, 71))
        self.graphButton.setObjectName("graphButton")
        self.temperatureAvgLabel = QtWidgets.QLabel(SensorInterface)
        self.temperatureAvgLabel.setGeometry(QtCore.QRect(50, 310, 61, 71))
        self.temperatureAvgLabel.setText("")
        self.temperatureAvgLabel.setPixmap(QtGui.QPixmap("Icons/temperatureAverage.png"))
        self.temperatureAvgLabel.setObjectName("temperatureAvgLabel")
        self.avgLabel1 = QtWidgets.QLabel(SensorInterface)
        self.avgLabel1.setGeometry(QtCore.QRect(110, 330, 31, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.avgLabel1.setFont(font)
        self.avgLabel1.setObjectName("avgLabel1")
        self.humidityAvgLabel = QtWidgets.QLabel(SensorInterface)
        self.humidityAvgLabel.setGeometry(QtCore.QRect(503, 315, 61, 61))
        self.humidityAvgLabel.setText("")
        self.humidityAvgLabel.setPixmap(QtGui.QPixmap("Icons/humidityAverage.png"))
        self.humidityAvgLabel.setObjectName("humidityAvgLabel")
        self.avgLabel2 = QtWidgets.QLabel(SensorInterface)
        self.avgLabel2.setGeometry(QtCore.QRect(563, 330, 31, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.avgLabel2.setFont(font)
        self.avgLabel2.setObjectName("avgLabel2")
        self.temperatureAvgDisplay = QtWidgets.QLCDNumber(SensorInterface)
        self.temperatureAvgDisplay.setGeometry(QtCore.QRect(50, 380, 101, 51))
        self.temperatureAvgDisplay.setObjectName("temperatureAvgDisplay")
        self.humidityAvgDisplay = QtWidgets.QLCDNumber(SensorInterface)
        self.humidityAvgDisplay.setGeometry(QtCore.QRect(500, 380, 101, 51))
        self.humidityAvgDisplay.setObjectName("humidityAvgDisplay")
        self.resetButton = QtWidgets.QPushButton(SensorInterface)
        self.resetButton.setGeometry(QtCore.QRect(30, 380, 21, 21))
        self.resetButton.setObjectName("resetButton")

        self.retranslateUi(SensorInterface)
        self.exitButton.clicked.connect(SensorInterface.close)
        QtCore.QMetaObject.connectSlotsByName(SensorInterface)

    def retranslateUi(self, SensorInterface):
        _translate = QtCore.QCoreApplication.translate
        SensorInterface.setWindowTitle(_translate("SensorInterface", "Form"))
        self.refreshButton.setText(_translate("SensorInterface", "Refresh"))
        self.exitButton.setText(_translate("SensorInterface", "Exit"))
        self.celciusButton.setText(_translate("SensorInterface", "C"))
        self.fahrenheitButton.setText(_translate("SensorInterface", "F"))
        self.timerStartButton.setText(_translate("SensorInterface", "Start Timer"))
        self.timerStopButton.setText(_translate("SensorInterface", "Stop Timer"))
        self.graphButton.setText(_translate("SensorInterface", "GRAPH"))
        self.avgLabel1.setText(_translate("SensorInterface", "AVG"))
        self.avgLabel2.setText(_translate("SensorInterface", "AVG"))
        self.resetButton.setText(_translate("SensorInterface", "R"))

