# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SensorUI.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SensorInterface(object):
    def setupUi(self, SensorInterface):
        SensorInterface.setObjectName("SensorInterface")
        SensorInterface.resize(850, 737)
        font = QtGui.QFont()
        font.setFamily("PibotoLt")
        SensorInterface.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/tempAvg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SensorInterface.setWindowIcon(icon)
        SensorInterface.setWindowOpacity(10.0)
        SensorInterface.setStyleSheet("background-color: rgb(43, 43, 43);\n"
"")
        self.refreshButton = QtWidgets.QPushButton(SensorInterface)
        self.refreshButton.setGeometry(QtCore.QRect(90, 640, 85, 85))
        self.refreshButton.setStyleSheet("")
        self.refreshButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/refreshbutton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshButton.setIcon(icon1)
        self.refreshButton.setIconSize(QtCore.QSize(70, 70))
        self.refreshButton.setObjectName("refreshButton")
        self.exitButton = QtWidgets.QPushButton(SensorInterface)
        self.exitButton.setGeometry(QtCore.QRect(680, 640, 85, 85))
        self.exitButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/powerbutton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitButton.setIcon(icon2)
        self.exitButton.setIconSize(QtCore.QSize(80, 80))
        self.exitButton.setAutoDefault(False)
        self.exitButton.setObjectName("exitButton")
        self.temperatureLabel = QtWidgets.QLabel(SensorInterface)
        self.temperatureLabel.setGeometry(QtCore.QRect(75, 40, 121, 131))
        self.temperatureLabel.setText("")
        self.temperatureLabel.setPixmap(QtGui.QPixmap("../../../Downloads/temperature.png"))
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.humidityLabel = QtWidgets.QLabel(SensorInterface)
        self.humidityLabel.setGeometry(QtCore.QRect(660, 40, 101, 131))
        self.humidityLabel.setText("")
        self.humidityLabel.setPixmap(QtGui.QPixmap("../../../Downloads/humidity.png"))
        self.humidityLabel.setObjectName("humidityLabel")
        self.timeLabel = QtWidgets.QLabel(SensorInterface)
        self.timeLabel.setGeometry(QtCore.QRect(380, 10, 91, 91))
        self.timeLabel.setText("")
        self.timeLabel.setPixmap(QtGui.QPixmap("Images/clock.png"))
        self.timeLabel.setObjectName("timeLabel")
        self.timeDisplay = QtWidgets.QLineEdit(SensorInterface)
        self.timeDisplay.setGeometry(QtCore.QRect(345, 110, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.timeDisplay.setFont(font)
        self.timeDisplay.setStyleSheet("color: rgb(255, 255, 255);")
        self.timeDisplay.setObjectName("timeDisplay")
        self.alertDisplay = QtWidgets.QLineEdit(SensorInterface)
        self.alertDisplay.setGeometry(QtCore.QRect(295, 340, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.alertDisplay.setFont(font)
        self.alertDisplay.setAutoFillBackground(False)
        self.alertDisplay.setStyleSheet("color: rgb(255, 255, 255);")
        self.alertDisplay.setObjectName("alertDisplay")
        self.alertLabel = QtWidgets.QLabel(SensorInterface)
        self.alertLabel.setGeometry(QtCore.QRect(380, 230, 91, 101))
        self.alertLabel.setText("")
        self.alertLabel.setPixmap(QtGui.QPixmap("../../../Downloads/alert.png"))
        self.alertLabel.setObjectName("alertLabel")
        self.temperatureDisplay = QtWidgets.QLCDNumber(SensorInterface)
        self.temperatureDisplay.setGeometry(QtCore.QRect(50, 180, 181, 81))
        self.temperatureDisplay.setStyleSheet("color: rgb(255, 255, 255);")
        self.temperatureDisplay.setObjectName("temperatureDisplay")
        self.humidityDisplay = QtWidgets.QLCDNumber(SensorInterface)
        self.humidityDisplay.setGeometry(QtCore.QRect(620, 180, 181, 81))
        self.humidityDisplay.setStyleSheet("color: rgb(255, 255, 255);")
        self.humidityDisplay.setObjectName("humidityDisplay")
        self.celciusButton = QtWidgets.QPushButton(SensorInterface)
        self.celciusButton.setGeometry(QtCore.QRect(18, 180, 31, 31))
        self.celciusButton.setStyleSheet("color: rgb(0, 0, 0);")
        self.celciusButton.setObjectName("celciusButton")
        self.fahrenheitButton = QtWidgets.QPushButton(SensorInterface)
        self.fahrenheitButton.setGeometry(QtCore.QRect(18, 230, 31, 31))
        self.fahrenheitButton.setStyleSheet("color: rgb(0, 0, 0);")
        self.fahrenheitButton.setObjectName("fahrenheitButton")
        self.timerButton = QtWidgets.QPushButton(SensorInterface)
        self.timerButton.setGeometry(QtCore.QRect(385, 640, 85, 85))
        self.timerButton.setStyleSheet("")
        self.timerButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Images/timerbutton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.timerButton.setIcon(icon3)
        self.timerButton.setIconSize(QtCore.QSize(80, 80))
        self.timerButton.setObjectName("timerButton")
        self.graphTempButton = QtWidgets.QPushButton(SensorInterface)
        self.graphTempButton.setGeometry(QtCore.QRect(340, 540, 85, 31))
        self.graphTempButton.setStyleSheet("color: rgb(0, 0, 0);")
        self.graphTempButton.setObjectName("graphTempButton")
        self.temperatureAvgLabel = QtWidgets.QLabel(SensorInterface)
        self.temperatureAvgLabel.setGeometry(QtCore.QRect(90, 435, 51, 61))
        self.temperatureAvgLabel.setText("")
        self.temperatureAvgLabel.setPixmap(QtGui.QPixmap("../../../Downloads/tempAvg.png"))
        self.temperatureAvgLabel.setObjectName("temperatureAvgLabel")
        self.avgLabel1 = QtWidgets.QLabel(SensorInterface)
        self.avgLabel1.setGeometry(QtCore.QRect(140, 435, 31, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.avgLabel1.setFont(font)
        self.avgLabel1.setStyleSheet("color: rgb(255, 255, 255);")
        self.avgLabel1.setObjectName("avgLabel1")
        self.humidityAvgLabel = QtWidgets.QLabel(SensorInterface)
        self.humidityAvgLabel.setGeometry(QtCore.QRect(670, 440, 51, 61))
        self.humidityAvgLabel.setText("")
        self.humidityAvgLabel.setPixmap(QtGui.QPixmap("../../../Downloads/humidityAvg.png"))
        self.humidityAvgLabel.setObjectName("humidityAvgLabel")
        self.avgLabel2 = QtWidgets.QLabel(SensorInterface)
        self.avgLabel2.setGeometry(QtCore.QRect(720, 440, 31, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.avgLabel2.setFont(font)
        self.avgLabel2.setStyleSheet("color: rgb(255, 255, 255);")
        self.avgLabel2.setObjectName("avgLabel2")
        self.temperatureAvgDisplay = QtWidgets.QLCDNumber(SensorInterface)
        self.temperatureAvgDisplay.setGeometry(QtCore.QRect(80, 500, 101, 51))
        self.temperatureAvgDisplay.setStyleSheet("color: rgb(255, 255, 255);")
        self.temperatureAvgDisplay.setObjectName("temperatureAvgDisplay")
        self.humidityAvgDisplay = QtWidgets.QLCDNumber(SensorInterface)
        self.humidityAvgDisplay.setGeometry(QtCore.QRect(660, 500, 101, 51))
        self.humidityAvgDisplay.setStyleSheet("color: rgb(255, 255, 255);")
        self.humidityAvgDisplay.setObjectName("humidityAvgDisplay")
        self.resetButton = QtWidgets.QPushButton(SensorInterface)
        self.resetButton.setGeometry(QtCore.QRect(50, 500, 21, 21))
        self.resetButton.setStyleSheet("color: rgb(0, 0, 0);")
        self.resetButton.setObjectName("resetButton")
        self.graphHumButton = QtWidgets.QPushButton(SensorInterface)
        self.graphHumButton.setGeometry(QtCore.QRect(430, 540, 85, 31))
        self.graphHumButton.setStyleSheet("color: rgb(0, 0, 0);")
        self.graphHumButton.setObjectName("graphHumButton")
        self.graphLabel = QtWidgets.QLabel(SensorInterface)
        self.graphLabel.setGeometry(QtCore.QRect(380, 450, 91, 81))
        self.graphLabel.setText("")
        self.graphLabel.setPixmap(QtGui.QPixmap("../../../Downloads/graph.png"))
        self.graphLabel.setObjectName("graphLabel")
        self.tempDial = QtWidgets.QDial(SensorInterface)
        self.tempDial.setGeometry(QtCore.QRect(50, 310, 61, 61))
        self.tempDial.setMinimum(-15)
        self.tempDial.setMaximum(35)
        self.tempDial.setSingleStep(2)
        self.tempDial.setObjectName("tempDial")
        self.humDial = QtWidgets.QDial(SensorInterface)
        self.humDial.setGeometry(QtCore.QRect(630, 310, 61, 61))
        self.humDial.setMinimum(10)
        self.humDial.setMaximum(80)
        self.humDial.setObjectName("humDial")
        self.tempThresholdDisplay = QtWidgets.QLCDNumber(SensorInterface)
        self.tempThresholdDisplay.setGeometry(QtCore.QRect(120, 325, 61, 31))
        self.tempThresholdDisplay.setStyleSheet("color: rgb(255, 255, 255);")
        self.tempThresholdDisplay.setDigitCount(3)
        self.tempThresholdDisplay.setObjectName("tempThresholdDisplay")
        self.humThresholdDisplay = QtWidgets.QLCDNumber(SensorInterface)
        self.humThresholdDisplay.setGeometry(QtCore.QRect(700, 325, 61, 31))
        self.humThresholdDisplay.setStyleSheet("color: rgb(255, 255, 255);")
        self.humThresholdDisplay.setDigitCount(3)
        self.humThresholdDisplay.setObjectName("humThresholdDisplay")
        self.tempThresholdLabel = QtWidgets.QLabel(SensorInterface)
        self.tempThresholdLabel.setGeometry(QtCore.QRect(190, 330, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tempThresholdLabel.setFont(font)
        self.tempThresholdLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.tempThresholdLabel.setObjectName("tempThresholdLabel")
        self.humThresholdLabel = QtWidgets.QLabel(SensorInterface)
        self.humThresholdLabel.setGeometry(QtCore.QRect(770, 330, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.humThresholdLabel.setFont(font)
        self.humThresholdLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.humThresholdLabel.setObjectName("humThresholdLabel")
        self.timerStatus = QtWidgets.QLineEdit(SensorInterface)
        self.timerStatus.setGeometry(QtCore.QRect(470, 640, 16, 16))
        self.timerStatus.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.timerStatus.setObjectName("timerStatus")
        self.sensorStatus = QtWidgets.QLineEdit(SensorInterface)
        self.sensorStatus.setGeometry(QtCore.QRect(415, 195, 21, 21))
        self.sensorStatus.setAutoFillBackground(False)
        self.sensorStatus.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.sensorStatus.setObjectName("sensorStatus")
        self.line = QtWidgets.QFrame(SensorInterface)
        self.line.setGeometry(QtCore.QRect(0, 610, 851, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(SensorInterface)
        self.line_2.setGeometry(QtCore.QRect(265, -10, 20, 751))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(SensorInterface)
        self.line_3.setGeometry(QtCore.QRect(565, -10, 20, 751))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.retranslateUi(SensorInterface)
        self.exitButton.clicked.connect(SensorInterface.close)
        QtCore.QMetaObject.connectSlotsByName(SensorInterface)

    def retranslateUi(self, SensorInterface):
        _translate = QtCore.QCoreApplication.translate
        SensorInterface.setWindowTitle(_translate("SensorInterface", "Sensor Interface"))
        self.celciusButton.setText(_translate("SensorInterface", "C"))
        self.fahrenheitButton.setText(_translate("SensorInterface", "F"))
        self.graphTempButton.setText(_translate("SensorInterface", "TEMP"))
        self.avgLabel1.setText(_translate("SensorInterface", "AVG"))
        self.avgLabel2.setText(_translate("SensorInterface", "AVG"))
        self.resetButton.setText(_translate("SensorInterface", "R"))
        self.graphHumButton.setText(_translate("SensorInterface", "HUM"))
        self.tempThresholdLabel.setText(_translate("SensorInterface", "TT"))
        self.humThresholdLabel.setText(_translate("SensorInterface", "HT"))

